---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: seatech-bot
spec:
  encryptedData:
    token: AgBRPfYHBjTW0qKAdHyrJeCCLbv8vMS7NFKQ8VdCSO4IECRxX5bNtxAw88tAZgcPJN+NR9a8THnW1FprEfVqhGST26CEaMVwGYlOfEeTucH6jkTPdJGCd/PynfjNQm16sXLXDt1E6YgUIuQMuE0WgbqWNIcALjasYIr/w/k/6xWVR6NzSCIoEata5hYFeLgarSVMhSKdwlgLhx7zB46ZO3xOv52TeejJ/N9b6Mu091wwxetAUjZjm2iN5NfOM0ViVyyXm3H3sKdxaAKlOVMQju6wKrEMbrGAiNmieOfUk4pS+59NdCNItrFVqzwT97CcsqnJSwPfhPOnxj1btmw7vQfzVwqCtw8UfTUGWwFn9mNOzcCuIKKYQ9YzchWd2R3X5s9Z46IPr42ZM4WHFNBgjvfXeeu66IdA8C61MIHLfpxV4/eDuSN3+MDu/DZL85nspVerNpzrMJ9v4xeW5BRYkAYx4AnR3tIsFDyiE+7nV+lU75KSD1guqBkiov+U1Lz0bNFS9HHj4ck8I/NO8swE8Dwf9LplWFDvM/6713RxzGftvutXaD6PwrklOqE83Rra7UPYtAw1aADyFfcrqEd97sDkP3BA72VhAazaVHJ4dWVeIe5wtCGJ9mb+MFhhEIw/+a8B7MUtgsZ7tLbtEEMAC2mW5+GEbafxVk6uivQLoIVh1B4tqJ+aPYok7FXJabd4LvLWxS3llATA86H+LE2NeYId0nzHcwqDy9Jxl8tMTAxK8JqKeduespTr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: seatech-bot
