---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apic-pipeline-git
  namespace: ci
spec:
  encryptedData:
    GIT_PRIV_TOKEN: AgBwapTJEozsLOjl+7ZaReJo6xOuxysGW/Prpju21iGTRydwLCGCi2UONsgjUXAToYtf3hxZeszQKyERAKKHmNa6I1K9frn3rJCumPLY/FlBHfel+PobtR1xYYuMbGJdzSslBT9KASOpev9vENAy7zraR6IzvyrI8MtPZ+GupJoxOUm+Bz4TDqokF3lujKQof1GqNB7v66L10qJHllm3Wvk1kozXG9m4fY+X2OFpFd51d5YgOT4Ta8ba/gWsSkz/RXS+4YDHpqwaLgrJl3YNIt9bP2QvOWh54PWc+MWJ0cmf6y6Mlzv5gHLiIz0vaa92Sqg7Bf3ZEwDG4JRFL660WPnjHnuq8k0hunYIMw5x0ZfUeWPJ9sXdcqpA73PHDQ8lIS6OePc+xXo6RxjdkWwUD2gral3s467qwaoNfRoB1WWc+xvGT7aSnUjcTkuOSNfEcBdppepk7GNpUN1Sm5Nxb5uNN+L7sWUJZmR00GDj0Y/WP67ikbNd2VB+Iq6ixLBXupT8Kg0Ok4+uqSnHz0UaxY9mKkE7PO0HydiglFrX7UEStUmXmLtaim93RmctlmXbdgjK8aJ71uf/RIo1WZ3gH3ggOyBcLtxraC4avRNzCLf9e969HJ8AuKBfUKc5ySc+UNAxdUEyOt0KnWqY5jgSK8NHIXadKMF4MMFCUMwW+lZPff28JmQ29jqLLVoLP9ftc1y6zxmfH+PByF+sEDFIsHEVrx7j0+P1RodTet0no7xJ21aKEbnbeAvq
    GIT_USERNAME: AgAiGyGIibvirbQxs+sZU7ebEnEcvOpG9Zc3Xc43p5RXVOV7EtQ01jtu0KAw1F6SxGj6/trLTvyNUq7f4wQn+05BrWVF1W/tdcfnd1anxSP9Xbpb/OuLCLYOFCekBQcZ2Db3uYH73d04PeebtpXIu1WB2s++fOHzigVR1h12guJqur+MW79u0BiXseFZyhdo1WuzIUrNpI5BHlZmmeDyOUWY//+OuxtSx1IgrYUaX1ZwTYIrtmkYvWPWv4Jh2u3aDhDxA8DKsVt7W5R5u3mhWWt4kMXh2mDKfzNxdMQDJFnzu4rU5tL0FGIckst55zvMl7CmkFWUxpKIlN4P3I7tqCswLN/Z+rh2S3hsFSrnaRMCdZg2pphEGTmIoCnY4A8Vp0Kz9iroEbc9uf0jdw8PYJ2GEt6M2Tj6judi3TdHPDi2yEKCFrqiM+v2TethD4R4X5JqkV68IsIZ/POQlbkyV4XSWqTjplHeS4cGaLC+Y4hFtmM66W9jx6rABWLlwyn0NUzlzWS0a1nhnXhubsI58DPxmgTDrUdkqUeBgk5mnSXGxu/YTkTThYxNV3RTjbdBgz6c80+7xsjf7/lQjdGocgi3BEUmNqrsIqs5mBFXtLgTRa0bg0qq0a7seL6y5ZHdRNPgy+SjCWH1plWNcOCHAsCtptSRmu19Uold7xxwvlGCwYkYmwF5X8JxtYvubLK8Yuh8f0CQdaxGJg==
  template:
    metadata:
      creationTimestamp: null
      name: apic-pipeline-git
      namespace: ci
