---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgBh5fP+EAZ3pvDrq6vLEls7hgsrCfSGL/RGHuZHGXg/GyNDY3YTSug7Y4IMcoGUMsHoEy+3tzV/S1VfJ/FsEUCw3zZ+FB391oCGQSjwwHDKXvaSpn/Q+QslaZO9At2gc93zVNUJi6qixAHmTsWQm81ZnoO9eRQjSOUU816yAXGKO+G9PygBrxLKvv0zbcpAsi+6v/qwDqdOYxrASH/rJQ5AFoMDomMbJofNnnnrOY8HwfIGplXGOtzkkmLMHE9agf4Rl2ueB5GBCCngbmX3tFD6AE0Qo2DLV8o9lc+hh312TJ5spFCd+kjviLGQxrvOHMwq0EdnBz/nu7xyO/KFMaVTo1l4ZUkuGoaNqo/YuSXWhXlQondXpxc3p06cQ+XUSMcQXqwTpR7AkOP7J7bN1qb6ItV4y35Slv/o+D+hCXY0muu14bL3j90Yr7A3bhpAI++24Tb0EfmY4t9G0lisBYLG0p01hWbATZJjjuMIPtXcU1dooWBTD6LtXo1fxqrZrcxCF71mHqrT1qqvrkWuZj9vmlf9smU5/m6U0CAB29EKb4DCy3YFpEDHouw9BYQqt+ByXJa0w/eY2YG6Fj72mXGP55WazmAv9HXw3w+leE7RrZdfledk6VOMA2QeCau+mPYlpo07pKzgr2gubA5nm47q0qrp8PJNIBiQMwcjdsPaU4agg3J/oy7uQ9yMb8p86aQtL2zZX40OJYTJ09O5Bt+d6yhgV3bDA0CSPQ1flZURsktuDSz0SQLTbFp5/DWYCk1OQ5ju3+ChLqXWQJm19RguSJGHkdWq7AqpKnIn3q5OCS2YknJxsu1TrBDHLG9qsIZA31rGcScUVe/DlKh38WYVUwO3V1RAD3Ia3FOLQxmdJbTmQ4su6prrYAcfY/9MH2hu+4NrGE9CsUsGVEOxVN/CJJbX4wObz95hjky5YCBJHfJVbIAz4lELWp7DyItXM8+mIz2dTu5b107yujYe51wBCrHYUcv5GOVEqjRNZKqAIQb2Qg0NrrIyu11PBBdsJbSBD3QDezUEvK26G4JBJtnuZdQ5H9b3FVT+qV0lU6j8gcRAXQzFeRgW640a2vjxr74IdOJew7va4G84RtHUYvGNuZ3eU8hDQ+xVecpNibgOQoiTFHX95ETT7QHzSkXxgKHpaiG5x+fmDNfrEJZaNdyTgmFBidzohTa1X7pRsWKMmu242oumxJszHbSpdGZc9BW9iXiquVDApfnLLwTIpBSDt9v9HtSfgi0mM+2QBJlJfvs63e/3SIO3ozktrxBA/3fy6qLy5d/YnS2lzV89rVuPEIx6lkZqTQ63KhoW3nKHffZajF2SyHyn7nCGAlSBhM3wkt7Rnl0v90feW7HXs7lVKfyBlobb0mgp9HGoY7bCR4C83g+L
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson
