---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgB+afZ6ZZXJOSFBewjJrGBE/rUFCfzjtu7FHtzAfQZ5LSZ7s0ZeTOmcfPN3857U7jUM8UZo+K1bQGT6Z3CO+WiyfVVRN6DZtZPEhicxYzNBpI3WXRrCc2P9V29Sz7m4srA7pmhAwivJya/aR8ShoLGHaRWrhrSDh4+k/KgFTkJ4Inc5HgjXnTFW1T4l4oeqZ9HC6DQXM+/5y+/Cug3ysSy/X/Muo9ieygvcxi7Q5RyY88Xpfe1826fZm5Mq7gkYgDaCGU1t/S76dgIap9CwlJLZ+BkuDrAh2ReDAB04wCyF2O7Xmks4QSLr4MSO5Wl6tMR9kZW4t+3jSMexWauScvW6BQzkqVV1saynpXTfaGyeFR73rXLJ9cYE+isEenmv5PAoNhhvtsrJ4kFo2jOybZXUU8q7MSCmTfxiOycZsggTYMNU+TvBGCHKRV8E9xd3K+u9GLDHLNS6doDq/9679DCUp9ObyenSLqsi1IsFyzk9pFQJYPjsVGzL8bVM0Kj2WW1f4SQ67nlwyKJEIF0X/qvwssG/3Wa7Y00HdDFbs6hp7atGEl41M3s2aOeOrl47/3eVEr47EXSaQM+5pkiYdQdI7XEtZldV14N8B2Nvkiv93yYP/qFOyb9npFY51GBv8w4ukmbWS57XzstnwfiZ1u/JZS+LT2o70CEqmWSYnB2aeQGHZD7bK1YSqmpxarcGx46488/1T/fBWhciOZz7H0Wwf+4ZchDDjUIGwGxaQkc/Dm1FpKplBWmJvILNTIwfSQZdKgYDXPy7ruAt34aBgsHLGHXFrM2AkDXDZ+9rwaZtH/OXkCM1IbhVfiKHzeaRnTapjI9l7f/LZpjgMeDYAgopvRuELAii5d0FPg4FC77EWS4EeJNC7Wl417Vp8KaOP3kiKfAJaLt7eq8YygLHfRXoLY5lopHwiRamVgaq3uENMrWKB7VUrgxxHlBdEvr9L5f2H31bzy30iUtq24bbiwrLOs35Db9nZZonTIjrO29h9O7F59oGuVia6YnmNe7I/A5iXJFCvJcwuI5JvsHnTRhYs4rh9olyqMyTf4+Gd7QG8RjnoEtQ12xuOCEnGxuC7cl/2c9n0ggIq7qQV6rCiYfDYQeimNbANVpowKTT/e+xigTHQwDcyrAqGQw198sjNntK3MAheSFTZKpK7peS9qg9GWeSvTHohDllzR6GferNGOas1cwoKz8c3tKs7Qsp1EcE0j+hQJ0ddEIySSybb8CbZmdiEfE961F2BrwjA6J1ltiQJfj8BSL4Nzyg8LmGmGgOaXgLZ+Q9o+94BKKlM/C0MjY7bmgbTZUnPVjv8EJ6pyH38iA10t96l+zVmicXU0EciPBDBfJat5g/lUVnslHLS8Wucr1WOg5Yd6fXiabadIxPFOvU
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson
