apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-integration-server
spec:
  storageClassName: integration-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem