---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgAO68MX0hO8W3p3Svg1aIoUUhV4SUhkqB3tEIyuseI8h2QeK/ZuaU/dX0pCaBRPwxLKZOysm01xjIt0ApAQizhSov82gXC/14xwP+3S/m35TzjCV7R7Tk85h5wz/26YMdUPf6gQUiSv1bV4/NX7+qhowVbilEsmM2DCyLTnkTqLEAjoSytsLNq7q9BBrLqZVe6p1fxb1dpjX8JXtibWBuPh9sKwergB1/9JCVt5uqELku2jMBeJm19SLeQXaYr9JeI63oobmYF0MlvMLBXLu2z0M9HsyaDhLShQWR0gSjXL+VTi8yaSE17TVgX0Cdj2u2mqOHwFKuxC1C84DRHAYS5bIQzP+NKRw/1sOaHXyV64kR4qvyulZNYsXY82mjcJEcM/QZVE66CK5px9uZG5af/r+qxTRlBPivzWYUmlmhN19z2L7MfeWAmjeHQLirRzpRzAOBnr1l+ShKZaw381r38UwbpZWz52ii3PG4rWNx921YsAJPSazbQvSmLS1WbTK0Un5XaJ7HdF29iWmjLwEzQDkbZmVp8e0PwcFWYHcvxN+YWAB2IKGQAoG+5HyWjbC6GlvRQvynpLVakRqlIyh+z5TYeQuSHvBQS1QwV8oWuofSoR9fHEkcFJg21zpBB5GkA5cwdEsWlLjPjmtPEWywrzFRIGOGsfTMzOcq4fHuHPA6CvzkUH/a6LiHuddcHdPwwkFbC1qn9eFPofdtMAGzGOsFWdYHSFm3oC+Pis+gpFlRzSH4aQTi17Mvt9ed2qH+agAoUlfZP0C8kfHuYJ/8Ene49hQpFziiton7ZXHmQIh6kjPFLflyoq7+dmx6ByL9s18vb3KmRHT8CEnB1SWbXARLpKInuoUeR+5hM9Xtany4u1KB9UjkUQxxaYPeSslg8JKxNMp/MyAnMqojenzkvYmj/fz5ujv4GR/BSJLrfXglVGX1ImPej7IWYtNOL6EdHYP/aSansq7eR5pnLGj+1T5CitEs84OSOofkf99YGf6mAC419aN30OPxyyzrHG72RL+RzmzE4VpGN5bnUI46YG+0Yz1NO4RkukZUb7iIY77VtemqBKW2ZuroLkAMXe8oi8HN0t/TaVVGS3Y/XPj6onw0GX6Dnw6MeE8H4xIx8B+GEUqqKNo4tcycJTO5nz1NJ6LZRm3RNj70CampAd8XMn1gYgc3ys7bsmRIeS24sV13Ny4c+5dPleX+wGGU7dIM/gJD7ciFf577qf4aDlK+/VbQbcSX507AdXAAM4M2V83Gb/d7oqkO+nmXN5wkQufkBTIe7LvN5qBylk2MfQBeatQcYL1nKnhg68aDN32u+QZXLVgdsKtA2HKOxbT7iIdYlrURNvPwTspN1jr2y6XmTulVVmOhfgNRXqtk+2KREK31N5zRFO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson
